/* Test the python script and ansible playbook */
pipeline {
    agent any
    stages {
        // Build the agent environment
        stage('Build') {
            steps {
                sh 'pip install virtualenv'
            }
        }
        // Verify
        stage('Verify') {
            steps {
                sh 'python3 --version'
            }
        }
        // Run script
        stage('Run the cmd') {
            steps {
                sh 'python3 -m virtualenv venv'
                sh """. venv/bin/activate
                pip install -r ./2_Jenkins/jenkins_example_scripts_python/requirements.txt
                ansible --version
                """
            }
        }
        stage('run ansible') {
            steps {
                sh 'python3 ./2_Jenkins/jenkins_example_scripts_python/hello.py'
            }
        }
    }
}