/* Test the python script and ansible playbook */
pipeline {
    agent any
    stages {
        // Build the agent environment
        stage('Build') {
            agent {
                docker {
                    image 'python:3-alpine' 
                }
                steps {
                    sh 'pip install virtualenv'
                }
            }
        }
        // Verify
        stage('Verify') {
            steps {
                sh 'python3 --version'
            }
        }
        // Run script
        stage('Run the cmd') {
            steps {
                sh 'python3 hello.py'
            }
        }
    }
}